<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WitnessSolver</RootNamespace>
    <AssemblyName>WitnessSolver.Puzzles</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WitnessSolver.Core\WitnessSolver.Core.csproj" />
  </ItemGroup>

</Project>
