<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>WitnessSolver</RootNamespace>
    <AssemblyName>WitnessSolver</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationIcon>witness.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WitnessSolver.Core\WitnessSolver.Core.csproj" />
    <ProjectReference Include="..\WitnessSolver.Puzzles\WitnessSolver.Puzzles.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="witness.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
